include:
  - project: 'node-bff/platform/ci/ci-base'
    ref: master
    file: '/github-ci/docker/generic/.github-ci-template.yml'

variables:
  APP_PORT: 3001

build-image:
  variables:
    DOCKERFILE: Dockerfile.test
